site_name: RJDS — Documentation
theme:
  name: material
  palette:
  - scheme: default
    primary: indigo
    toggle:
      icon: material/brightness-7
      name: Switch to dark
  - scheme: slate
    primary: indigo
    toggle:
      icon: material/brightness-4
      name: Switch to light
  features:
  - content.code.copy
markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.superfences: {}
- tables
nav:
- Home: index.md
- php-humanize: projects/php-humanize/index.md
- php-slugify: projects/php-slugify/index.md
repo_url: https://github.com/RubenJ01/libraries-wiki-docs
repo_name: RubenJ01/libraries-wiki-docs
